# Generated by Django 3.2 on 2022-12-19 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('face_id', models.AutoField(primary_key=True, serialize=False)),
                ('face_name', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'face',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopFile',
            fields=[
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.shop')),
                ('main_img', models.CharField(blank=True, max_length=250, null=True)),
                ('img1', models.CharField(blank=True, max_length=250, null=True)),
                ('img2', models.CharField(blank=True, max_length=250, null=True)),
                ('img3', models.CharField(blank=True, max_length=250, null=True)),
                ('img4', models.CharField(blank=True, max_length=250, null=True)),
                ('img5', models.CharField(blank=True, max_length=250, null=True)),
                ('regdatetime', models.DateTimeField(blank=True, null=True)),
                ('updatedatetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shop_file',
                'managed': False,
            },
        ),
    ]
