# Generated by Django 3.2 on 2022-12-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221226_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthtokenToken',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='BoardFile',
        ),
        migrations.RemoveField(
            model_name='boardreview',
            name='board',
        ),
        migrations.RemoveField(
            model_name='codedetail',
            name='class_field',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.RemoveField(
            model_name='priceinfo',
            name='shop',
        ),
        migrations.DeleteModel(
            name='UserinfoDetail',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo_detail',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='BoardReview',
        ),
        migrations.DeleteModel(
            name='CodeDetail',
        ),
        migrations.DeleteModel(
            name='CodeMaster',
        ),
        migrations.DeleteModel(
            name='Priceinfo',
        ),
    ]
