# Generated by Django 3.2 on 2022-12-29 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221229_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserinfoDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.userinfo')),
                ('skin_condition', models.CharField(blank=True, max_length=10, null=True)),
                ('hair_bold', models.CharField(blank=True, max_length=10, null=True)),
                ('curl', models.CharField(blank=True, max_length=10, null=True)),
                ('hair_condition', models.CharField(blank=True, max_length=10, null=True)),
                ('thick_hair', models.CharField(blank=True, max_length=10, null=True)),
                ('hair_age', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('regdatetime', models.DateTimeField(blank=True, null=True)),
                ('updatedatetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userinfo_detail',
                'managed': False,
            },
        ),
    ]
