# Generated by Django 3.2 on 2022-12-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userinfodetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
